version: "3.5"

services:
    etardis-graph:
        build: ./src/crawling
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - ./data/neo4j_data:/data
        environment:
            NEO4J_dbms_memory_pagecache_size: 4G
            NEO4J_AUTH: neo4j/password
        restart: on-failure
        networks:
            - etardis-network

    etardis-api:
        build: ./src/api
        depends_on:
            - etardis-graph
        links:
            - etardis-graph
        ports:
            - "5000:5000"
        volumes:
            - ./data:/data
        expose:
            - "5000"
        environment:
            FLASK_APP: graph_api.py
            FLASK_ENV: development
            FLASK_DEBUG: 1
            NEO4J_URL: etardis-graph
            NEO4J_BOLT_PORT: 7687
            NEO4J_USER: neo4j
            NEO4J_PASSWD: password
        restart: on-failure
        networks:
            - etardis-network

    etardis-frontend:
        build: ./src/frontend
        depends_on:
            - etardis-api
        ports:
            - "3000:3000"
        restart: on-failure
        networks:
            - etardis-network

networks:
    etardis-network:
