version: '3.5'

services:
    etardis-graph:
        build: ./src/crawling
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - ./data/neo4j_data:/data
        environment:
            NEO4J_dbms_memory_pagecache_size: 4G
            NEO4J_AUTH: neo4j/password
        restart: on-failure
